# Generated by Django 2.1 on 2019-10-10 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='event',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member',
        ),
        migrations.RemoveField(
            model_name='event',
            name='carry',
        ),
        migrations.RemoveField(
            model_name='event',
            name='free',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='private',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='participations',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_event', to='Events.Event'),
        ),
        migrations.AddField(
            model_name='participations',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
