# Generated by Django 2.1 on 2019-10-11 00:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0002_auto_20191011_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participations',
            new_name='Participation',
        ),
    ]
