# Generated by Django 2.1 on 2019-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20191011_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
