# Generated by Django 2.1 on 2019-10-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_notification_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(upload_to='images/events'),
        ),
    ]
